package com.example.createmonster.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFF1C100)
val md_theme_light_onPrimary = Color(0xFF371409)
val md_theme_light_primaryContainer = Color(0xFFFFE08B)
val md_theme_light_onPrimaryContainer = Color(0xFF371409)
val md_theme_light_secondary = Color(0xFF00de3c)
val md_theme_light_onSecondary = Color(0xFF371409)
val md_theme_light_secondaryContainer = Color(0xFF9dff7a)
val md_theme_light_onSecondaryContainer = Color(0xFF371409)
val md_theme_light_tertiary = Color(0xFF0060A9)
val md_theme_light_onTertiary = Color(0xFF371409)
val md_theme_light_tertiaryContainer = Color(0xFFD3E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF371409)
val md_theme_light_error = Color(0xFFF44937)
val md_theme_light_errorContainer = Color(0xFFFca285)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF371409)
val md_theme_light_background = Color(0xFF5BA7E4)
val md_theme_light_onBackground = Color(0xFF371409)
val md_theme_light_surface = Color(0xFF5BA7E4)
val md_theme_light_onSurface = Color(0xFF371409)
val md_theme_light_surfaceVariant = Color(0xFFEBE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF371409)
val md_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFF1C100)
val md_theme_light_surfaceTint = Color(0xFF745B00)
val md_theme_light_outlineVariant = Color(0xFFCFC6B4)
val md_theme_light_scrim = Color(0xFF000000)